version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:476a1024936901889147f53d2a3d8e71e99d76404972d583825514f5608083dc
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: 349414613217.dkr.ecr.eu-central-1.amazonaws.com/junit-annotate:latest@sha256:187574ffdba0fcbfc725dc8dbf92cfba300aee9576130ac95d6c79bb3a5f6707
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"
